import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import React, { useState } from "react";
import Display from "../components/display";
import ButtonPanel from "../components/buttanpanel"; // Fix typo: "buttanpanel" -> "buttonpanel"
import calculate from "../scripts/calculate"; // Fix import: remove curly braces
import type { State } from "../scripts/calculate"; //

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [state, setState] = useState<State>({
    current: "0",
    operand: 0,
    operator: null,
    isNextClear: false,
    selectedOperator: null,
  });

  const calculatorBtn = (code: string) => {
    const nextState = calculate(code, state);
    setState(nextState);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <Display value={state.current} />
          <ButtonPanel
            calculatorBtn={calculatorBtn}
            selectedOperator={state.selectedOperator}
          />
        </div>
      </main>
    </>
  );
}
